image: khos2ow/ci-cd-tools

stages:
  - test
  - publish
  - deploy

variables:
  MAVEN_OPTS: '-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=INFO 
               -Dorg.slf4j.simpleLogger.showDateTime=true 
               -Djava.awt.headless=true
               -Dmaven.repo.local=/root/.m2/repository'

test:
  stage: test
  script:
    - test_verify
  artifacts:
    name: "test_code_quality_report_${CI_BUILD_REF_SLUG}"
    paths:
      - "*/*/target/pmd.xml"
      - "*/*/target/surefire-reports"
    when: on_failure
    expire_in: 1 day
  except:
    - tags

publish:
  stage: publish
  script:
    - setup_docker
    - publish_docker
  only:
    - master

deploy:
  stage: deploy
  script:
    - "curl -X POST -F token=${PIPELINE_TRIGGER_TOKEN} -F ref=master https://gitlab.com/api/v4/projects/${PIPELINE_TRIGGER_PROJECT}/trigger/pipeline"
  only:
    - master

.auto_config: &auto_config |

  function test_verify() {
    ./mvnw clean verify --batch-mode --show-version
  }

  function setup_docker() {
    if ! docker info &>/dev/null; then
      if [ -z "$DOCKER_HOST" ]; then
        export DOCKER_HOST='tcp://localhost:2375'
      fi
    fi
  }

  function publish_docker() {
    ./mvnw clean -q &> /dev/null
    local pom_version=`./mvnw org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version | grep -v '\[' | grep -v '\/' | grep -v 'Warning' | tr "[:upper:]" "[:lower:]" | tr -d "\r"`
    ./mvnw verify --activate-profiles production \
                  --batch-mode \
                  -DskipTests=true \
                  -DpushImage \
                  -DpushTags \
                  -Ddocker.image.version="${pom_version}" \
                  --show-version \
                  --settings settings.xml
  }

before_script:
  - *auto_config

