image: khos2ow/ci-cd-tools

stages:
  - test
  - publish
  - deploy

variables:
  MAVEN_OPTS: '-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=INFO
               -Dorg.slf4j.simpleLogger.showDateTime=true
               -Djava.awt.headless=true
               -Dmaven.repo.local=/root/.m2/repository'

test:
  stage: test
  script:
    - make clean test
  artifacts:
    name: "test_code_quality_report_${CI_BUILD_REF_SLUG}"
    paths:
      - "*/*/target/pmd.xml"
      - "*/*/target/surefire-reports"
    when: on_failure
    expire_in: 1 day
  except:
    - tags

publish:
  stage: publish
  script:
    - setup_docker
    - make build-push
  only:
    - master

deploy:
  stage: deploy
  script:
    - "curl -X POST -F token=${PIPELINE_TRIGGER_TOKEN} -F ref=master https://gitlab.com/api/v4/projects/${PIPELINE_TRIGGER_PROJECT}/trigger/pipeline"
  only:
    - master

.auto_config: &auto_config |

  function setup_docker() {
    if ! docker info &>/dev/null; then
      if [ -z "$DOCKER_HOST" ]; then
        export DOCKER_HOST='tcp://localhost:2375'
      fi
    fi
  }

before_script:
  - *auto_config

