version: '2.2'

services:
  # Application
  app:
    image: registry.gitlab.com/khos2ow/fifawc18 
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=fifawc18
    depends_on:
      mysql:
        condition: service_healthy

  # Database
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fifawc18
      MYSQL_PASSWORD: root
    volumes:
      - ./data/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
