spring:
  application:
    name: FIFA World Cup 2018 Prediction Game

  profiles:
    active:
      - ${profiles.active:@profile.active@}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
          
security:
  oauth2:
    client:
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
      scope: profile email
    resource:
      userInfoUri: https://www.googleapis.com/userinfo/v2/me
      preferTokenInfo: false

server:
  port: 8080

management:
  server:
    port: 9000

logging:
  level:
    org:
      springframework:
        retry: ${log.level:@log.level@}

    io:
      khosrow:
        fifawc: ${log.level:@log.level@}

---

spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://localhost:3306/fifawc18?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: root
    password: cloudops

  jpa:
    hibernate:
      ddlAuto: update

security:
  oauth2:
    client:
      clientId: ${OAUTH_CLIENT_ID_DEV}
      clientSecret: ${OAUTH_CLIENT_SECRET_DEV}

---

spring:
  profiles: prod

  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

security:
  oauth2:
    client:
      clientId: ${OAUTH_CLIENT_ID}
      clientSecret: ${OAUTH_CLIENT_SECRET}
