version: '2.2'

services:
  # Nginx
  nginx:
    container_name: fifawc18_nginx
    image: nginx:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      app:
        condition: service_healthy
    
  # Application
  app:
    container_name: fifawc18_app
    image: registry.gitlab.com/khos2ow/fifawc18:latest
    restart: always
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=fifawc18
      - OAUTH_CLIENT_ID=xxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com
      - OAUTH_CLIENT_SECRET=yyyyyyyyyyyyyyyyy
    depends_on:
      mysql:
        condition: service_healthy

  # Database
  mysql:
    container_name: fifawc18_mysql
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fifawc18
      MYSQL_PASSWORD: root
    volumes:
      - ./data/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

